export const TypographyStyles = {
  h1: "text-4xl font-bold mb-4",
  h2: "text-3xl font-bold mb-3",
  h3: "text-2xl font-semibold mb-2",
  h4: "text-xl font-semibold mb-2",
  h5: "text-lg font-semibold mb-1",
  h6: "text-base font-semibold mb-1",
  subtitle1: "text-lg text-gray-700 mb-1",
  subtitle2: "text-base text-gray-600 mb-1",
  body1: "text-base text-gray-800",
  body2: "text-sm text-gray-700",
  caption: "text-xs text-gray-500",
  "banner-yellow": "bg-yellow-50 border-l-4 border-yellow-400 text-yellow-800 p-3 rounded mb-2",
  "banner-red": "bg-red-50 border-l-4 border-red-400 text-red-800 p-3 rounded mb-2",
  "banner-green": "bg-green-50 border-l-4 border-green-400 text-green-800 p-3 rounded mb-2",
  blockquote: "text-gray-700 italic mb-2",
  code: "text-sm font-mono bg-gray-100 p-2 rounded mb-2",
  "banner-blue": "bg-blue-50 border-l-4 border-blue-400 text-blue-800 p-3 rounded mb-2",
};
